# Generated by Django 5.0.2 on 2024-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
