# Generated by Django 5.0.2 on 2024-05-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_is_present'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
